<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Lauteur extends \App\Entity\Lauteur implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Lauteur' . "\0" . 'idlauteur', '' . "\0" . 'App\\Entity\\Lauteur' . "\0" . 'lelog', '' . "\0" . 'App\\Entity\\Lauteur' . "\0" . 'lepass', '' . "\0" . 'App\\Entity\\Lauteur' . "\0" . 'lenomcomplet'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Lauteur' . "\0" . 'idlauteur', '' . "\0" . 'App\\Entity\\Lauteur' . "\0" . 'lelog', '' . "\0" . 'App\\Entity\\Lauteur' . "\0" . 'lepass', '' . "\0" . 'App\\Entity\\Lauteur' . "\0" . 'lenomcomplet'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Lauteur $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdlauteur(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdlauteur();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdlauteur', []);

        return parent::getIdlauteur();
    }

    /**
     * {@inheritDoc}
     */
    public function getLelog(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLelog', []);

        return parent::getLelog();
    }

    /**
     * {@inheritDoc}
     */
    public function setLelog(string $lelog): \App\Entity\Lauteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLelog', [$lelog]);

        return parent::setLelog($lelog);
    }

    /**
     * {@inheritDoc}
     */
    public function getLepass(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLepass', []);

        return parent::getLepass();
    }

    /**
     * {@inheritDoc}
     */
    public function setLepass(string $lepass): \App\Entity\Lauteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLepass', [$lepass]);

        return parent::setLepass($lepass);
    }

    /**
     * {@inheritDoc}
     */
    public function getLenomcomplet(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLenomcomplet', []);

        return parent::getLenomcomplet();
    }

    /**
     * {@inheritDoc}
     */
    public function setLenomcomplet(string $lenomcomplet): \App\Entity\Lauteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLenomcomplet', [$lenomcomplet]);

        return parent::setLenomcomplet($lenomcomplet);
    }

}
