<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMQWM0xZ\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMQWM0xZ/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMQWM0xZ.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMQWM0xZ\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerMQWM0xZ\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'MQWM0xZ',
    'container.build_id' => '1e36df2d',
    'container.build_time' => 1540236993,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerMQWM0xZ');
